### ISSUE TITLE
Enhancement: ability to make factoids execute a simple commands like ?choice

### ISSUE THREAD

**Issue by ShadowBourne** [SunDwarf/NavalBot#10]
So instead of the factoid being ?"____" is "___" you could have ?"__" ?choice "no" "yes" or simply "either" instead of an "is" query (i think thats the term) ( i also think this is probs a better idea)
Also i asked JaytheSheep to ask you(well idk who) to update the wiki commands to include pause and resume but remove is also missing and i cant find anything about the factoids(i just found them randomly) so im assuming there may also be quite alot of stuff missing from the wiki at the moment, would love to see it fully up to date :)

**Comment by ilevn** [comment]
I updated the wiki accordingly. Unfortunately we wont change the factoid creation syntax
